/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/opcao-1/details` | `/opcao-1/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/opcao-1` | `/opcao-1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/opcao-2` | `/opcao-2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/opcao-3` | `/opcao-3`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/opcao-1/details` | `/opcao-1/details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/opcao-1` | `/opcao-1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/opcao-2` | `/opcao-2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/opcao-3` | `/opcao-3`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/opcao-1/details${`?${string}` | `#${string}` | ''}` | `/opcao-1/details${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/opcao-1${`?${string}` | `#${string}` | ''}` | `/opcao-1${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/opcao-2${`?${string}` | `#${string}` | ''}` | `/opcao-2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/opcao-3${`?${string}` | `#${string}` | ''}` | `/opcao-3${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/opcao-1/details` | `/opcao-1/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/opcao-1` | `/opcao-1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/opcao-2` | `/opcao-2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/opcao-3` | `/opcao-3`; params?: Router.UnknownInputParams; };
    }
  }
}
